/* title: Errorlog-Writer

   Writes error log text. This is only a wrapper module
   which includes the source file generated with text resource compiler.

   about: Copyright
   This program is free software.
   You can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   Author:
   (C) 2012 Jörg Seebohn

   file: C-kern/api/io/writer/log/errlog_macros.h
    Header file of <ErrlogMacros>.

   file: C-kern/io/writer/errlog.c
    Implementation file <Errorlog-Writer>.
*/

#include "C-kern/konfig.h"
#include "C-kern/api/err.h"
#include "C-kern/api/io/writer/log/logbuffer.h"
#include "C-kern/resource/generated/errlog.h"

#define PRINTF(...)   printf_logbuffer(logbuffer, __VA_ARGS__)

// generated by text resource compiler

#define KONFIG_de de
#define KONFIG_en en
#include STR(C-kern/resource/generated/errlog.KONFIG_LANG)
#undef KONFIG_de
#undef KONFIG_en
