/*
 * C source code generated by textresource compiler v2
 *
 * Do not edit this file -- instead edit 'C-kern/resource/logerror2.text'
 *
 */

#include "C-kern/konfig.h"
#include "C-kern/api/resource/logerrtext.h"
#include "C-kern/api/err.h"

#define PRINTF(...)  log_maincontext().functable->printf(log_maincontext().object, channel, __VA_ARGS__ )

#define de   1
#define en   2

#if ((KONFIG_LANG) & de)

int LOG_ERRTEXT_ABORT_ASSERT_FAILED(log_channel_e channel, int err, const char * wrong_condition)
{
   PRINTF("%d: Assertion '%s' fehlgeschlagen.\n", err, wrong_condition) ;
   return 0;
}

int LOG_ERRTEXT_ABORT_FATAL(log_channel_e channel, int err)
{
   PRINTF("%d: Programmabbruch wegen fatalem Fehler\n", err) ;
   return 0;
}

int LOG_ERRTEXT_ERROR_LOCATION(log_channel_e channel, const char * filename, int linenr, const char * funcname)
{
   PRINTF("%s:%d: %s(): Fehler: ", filename, linenr, funcname) ;
   return 0;
}

int LOG_ERRTEXT_FILE_FORMAT_MISSING_ENDOFLINE(log_channel_e channel, const char * filename)
{
   PRINTF("'%s' enthält kein Zeilenendezeichen\n", filename) ;
   return 0;
}

int LOG_ERRTEXT_FILE_FORMAT_WRONG(log_channel_e channel, const char * filename)
{
   PRINTF("Datei '%s' besitzt unbekanntes Format\n", filename) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ABORT(log_channel_e channel, int err)
{
   PRINTF("%d: Funktion abgebrochen\n", err) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ABORT_FREE(log_channel_e channel, int err)
{
   PRINTF("%d: Freigabe einer Ressource schlug fehl\n", err) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ERROR(log_channel_e channel, const char * funcname, int err, const char * errstr)
{
   PRINTF("%d: Funktionsaufruf '%s' meldet Fehler '%s'\n", err, funcname, errstr) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_SYSERR(log_channel_e channel, const char * funcname, int sys_errno, const char * sys_errstr)
{
   PRINTF("%d: Systemaufruf '%s' meldet Fehler '%s'\n", sys_errno, funcname, sys_errstr) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_WRONG_RETURNVALUE(log_channel_e channel, const char * funcname, const char * wrong_value)
{
   PRINTF("Funktion '%s' liefert falschen Rückgabewert (%s)\n", funcname, wrong_value) ;
   return 0;
}

int LOG_ERRTEXT_LOCALE_SETLOCALE(log_channel_e channel)
{
   PRINTF("Kann die Lokalisierung mit setlocale nicht setzen\nAbhilfe: Bitte die Umgebungsvariable LC_ALL auf einen vom System unterstützten Wert setzen\n") ;
   return 0;
}

int LOG_ERRTEXT_LOG_ENTRY_TRUNCATED(log_channel_e channel, int before_size, int after_size)
{
   PRINTF("Logeintrag gekürzt von %d auf %d Bytes\n", before_size, after_size) ;
   return 0;
}

int LOG_ERRTEXT_MEMORY_OUT_OF(log_channel_e channel, size_t size)
{
   PRINTF("Keine %zu Bytes Speicher mehr frei\n", size) ;
   return 0;
}

int LOG_ERRTEXT_PARAMETER_INT_TOO_BIG(log_channel_e channel, const char * parameter_name, int parameter_max)
{
   PRINTF("Parameter '%s' > %d\n", parameter_name, parameter_max) ;
   return 0;
}

int LOG_ERRTEXT_RESOURCE_USAGE_DIFFERENT(log_channel_e channel)
{
   PRINTF("Ungleiche Anzahl benutzter Ressourcen\n") ;
   return 0;
}

int LOG_ERRTEXT_TEST_INPARAM_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Eingabewert verletzt Bedingung (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_INVARIANT_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Interne Zustandsvariablen verletzen Bedingung (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_OUTPARAM_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Ausgabewert verletzt Bedingung (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_STATE_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Operation nur erlaubt im Zustand (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_X11_DISPLAY_NOT_SET(log_channel_e channel)
{
   PRINTF("Name des X11 Display-Servers nicht bekannt\nBitte die Umgebungsvariable »DISPLAY« setzen\n") ;
   return 0;
}

int LOG_ERRTEXT_X11_NO_CONNECTION(log_channel_e channel, const char * display_server_name)
{
   PRINTF("Keine Verbindung zu X11 Display-Server '%s'\n", display_server_name) ;
   return 0;
}

#elif ((KONFIG_LANG) & en)

int LOG_ERRTEXT_ABORT_ASSERT_FAILED(log_channel_e channel, int err, const char * wrong_condition)
{
   PRINTF("%d: Assertion '%s' failed.\n", err, wrong_condition) ;
   return 0;
}

int LOG_ERRTEXT_ABORT_FATAL(log_channel_e channel, int err)
{
   PRINTF("%d: Abort process with fatal error\n", err) ;
   return 0;
}

int LOG_ERRTEXT_ERROR_LOCATION(log_channel_e channel, const char * filename, int linenr, const char * funcname)
{
   PRINTF("%s:%d: %s(): error: ", filename, linenr, funcname) ;
   return 0;
}

int LOG_ERRTEXT_FILE_FORMAT_MISSING_ENDOFLINE(log_channel_e channel, const char * filename)
{
   PRINTF("'%s' contains no newline\n", filename) ;
   return 0;
}

int LOG_ERRTEXT_FILE_FORMAT_WRONG(log_channel_e channel, const char * filename)
{
   PRINTF("File '%s' has unknown format\n", filename) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ABORT(log_channel_e channel, int err)
{
   PRINTF("%d: Function aborted\n", err) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ABORT_FREE(log_channel_e channel, int err)
{
   PRINTF("%d: Freeing a resource returned an error\n", err) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_ERROR(log_channel_e channel, const char * funcname, int err, const char * errstr)
{
   PRINTF("%d: Function call '%s' returned error '%s'\n", err, funcname, errstr) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_SYSERR(log_channel_e channel, const char * funcname, int sys_errno, const char * sys_errstr)
{
   PRINTF("%d: System call '%s' returned error '%s'\n", sys_errno, funcname, sys_errstr) ;
   return 0;
}

int LOG_ERRTEXT_FUNCTION_WRONG_RETURNVALUE(log_channel_e channel, const char * funcname, const char * wrong_value)
{
   PRINTF("Function '%s' returned wrong value (%s)\n", funcname, wrong_value) ;
   return 0;
}

int LOG_ERRTEXT_LOCALE_SETLOCALE(log_channel_e channel)
{
   PRINTF("Cannot change the current locale with setlocale\nRemedy: Please set environment variable LC_ALL to a supported value by the system\n") ;
   return 0;
}

int LOG_ERRTEXT_LOG_ENTRY_TRUNCATED(log_channel_e channel, int before_size, int after_size)
{
   PRINTF("Log entry truncated from %d to %d bytes\n", before_size, after_size) ;
   return 0;
}

int LOG_ERRTEXT_MEMORY_OUT_OF(log_channel_e channel, size_t size)
{
   PRINTF("Could not allocate %zu bytes of memory\n", size) ;
   return 0;
}

int LOG_ERRTEXT_PARAMETER_INT_TOO_BIG(log_channel_e channel, const char * parameter_name, int parameter_max)
{
   PRINTF("Parameter '%s' > %d\n", parameter_name, parameter_max) ;
   return 0;
}

int LOG_ERRTEXT_RESOURCE_USAGE_DIFFERENT(log_channel_e channel)
{
   PRINTF("The number of used resources is different\n") ;
   return 0;
}

int LOG_ERRTEXT_TEST_INPARAM_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Function input violates condition (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_INVARIANT_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Internal state variables violate condition (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_OUTPARAM_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Function output violates condition (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_TEST_STATE_FALSE(log_channel_e channel, int err, const char * violated_condition)
{
   PRINTF("%d: Operation allowed only in state (%s)\n", err, violated_condition) ;
   return 0;
}

int LOG_ERRTEXT_X11_DISPLAY_NOT_SET(log_channel_e channel)
{
   PRINTF("Default name of X11 display servers unknown\nPlease set environment variable »DISPLAY«\n") ;
   return 0;
}

int LOG_ERRTEXT_X11_NO_CONNECTION(log_channel_e channel, const char * display_server_name)
{
   PRINTF("Can not connect to X11 display server '%s'\n", display_server_name) ;
   return 0;
}

#endif

#undef de
#undef en
