# (c) 2010 Jörg Seebohn

.PHONY: all Debug Release

TRC=rm -f $(@); trc=bin/textrescompiler; if [ ! -f $${trc} ]; then trc=$${trc}_Debug ; fi ; $${trc} -c $(@) --switch KONFIG_LANG $(<)

all: C-kern/api/resource/errorlog.h
Debug: all
Release: all

C-kern/api/resource/errorlog.h: C-kern/resource/errorlog.text
	@$(TRC)


