##
## ! Genmake generated Makefile !
##
ProjectName     := test
ProjectModes    := Debug Release
PathOffset      := 
ProjectFile     := $(PathOffset)projekte/test.prj
ProjectLinks    := 

GenerationDate  := 2011.May.07  05:06:48
GeneratedBy     := Jörg Seebohn

## Debug
DefineFlag_Debug    := -D
IncludeFlag_Debug   := -I
LibraryFlag_Debug   := -l
LibPathFlag_Debug   := -L
CFlags_Debug        := -g -MMD -std=gnu99 -pedantic -Wall -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wstrict-prototypes -Wformat-nonliteral -Wformat-y2k
LFlags_Debug        := -g 
Defines_Debug       := $(DefineFlag_Debug)KONFIG_UNITTEST
Includes_Debug      := $(IncludeFlag_Debug)$(PathOffset).
Libraries_Debug     := $(LibraryFlag_Debug)pthread $(LibraryFlag_Debug)rt
Libpath_Debug       :=
ObjectDir_Debug     := $(PathOffset)bin/Debug/test
TargetDir_Debug     := $(PathOffset)bin
Target_Debug        := $(PathOffset)bin/test_Debug
Libs_Debug          := $(Libpath_Debug) $(Libraries_Debug)
CC_Debug            = gcc $(Defines_Debug) $(Includes_Debug) $(CFlags_Debug) -c -o '$@' '$<'
LD_Debug            = gcc $(LFlags_Debug) -o '$@' $(foreach obj,$^,'$(obj)') $(Libs_Debug)

## Release
DefineFlag_Release    := -D
IncludeFlag_Release   := -I
LibraryFlag_Release   := -l
LibPathFlag_Release   := -L
CFlags_Release        := -O2 -MMD -std=gnu99 -pedantic -Wall -Wextra -Wconversion -Wshadow -Wcast-qual -Wwrite-strings -Wstrict-prototypes -Wformat-nonliteral -Wformat-y2k
LFlags_Release        := -O2 
Defines_Release       := $(DefineFlag_Release)KONFIG_UNITTEST
Includes_Release      := $(IncludeFlag_Release)$(PathOffset).
Libraries_Release     := $(LibraryFlag_Release)pthread $(LibraryFlag_Release)rt
Libpath_Release       :=
ObjectDir_Release     := $(PathOffset)bin/Release/test
TargetDir_Release     := $(PathOffset)bin
Target_Release        := $(PathOffset)bin/test
Libs_Release          := $(Libpath_Release) $(Libraries_Release)
CC_Release            = gcc $(Defines_Release) $(Includes_Release) $(CFlags_Release) -c -o '$@' '$<'
LD_Release            = gcc $(LFlags_Release) -o '$@' $(foreach obj,$^,'$(obj)') $(Libs_Release)

##
## Targets
##
all:   Debug Release
clean: clean_Debug clean_Release
init:  init_Debug init_Release
init_Debug: $(ObjectDir_Debug) $(TargetDir_Debug)
init_Release: $(ObjectDir_Release) $(TargetDir_Release)

Debug: $(Target_Debug)

Release: $(Target_Release)

clean_Debug:
	@rm -f "$(ObjectDir_Debug)/"*.[od]
	@rm -f "$(Target_Debug)"
	@if [ -d "$(ObjectDir_Debug)" ]; then rmdir -p --ignore-fail-on-non-empty "$(ObjectDir_Debug)"; fi
	@if [ -d "$(TargetDir_Debug)" ]; then rmdir -p --ignore-fail-on-non-empty "$(TargetDir_Debug)"; fi

clean_Release:
	@rm -f "$(ObjectDir_Release)/"*.[od]
	@rm -f "$(Target_Release)"
	@if [ -d "$(ObjectDir_Release)" ]; then rmdir -p --ignore-fail-on-non-empty "$(ObjectDir_Release)"; fi
	@if [ -d "$(TargetDir_Release)" ]; then rmdir -p --ignore-fail-on-non-empty "$(TargetDir_Release)"; fi

$(sort $(ObjectDir_Debug) $(TargetDir_Debug) $(ObjectDir_Release) $(TargetDir_Release)):
	@mkdir -p "$@"

Objects_Debug := \
 $(ObjectDir_Debug)/C-kern!main!test.c.o \
 $(ObjectDir_Debug)/C-kern!test!run_unittest.c.o \
 $(ObjectDir_Debug)/C-kern!os!Linux!directory.c.o \
 $(ObjectDir_Debug)/C-kern!os!Linux!thread.c.o \
 $(ObjectDir_Debug)/C-kern!os!Linux!virtmemory.c.o \
 $(ObjectDir_Debug)/C-kern!os!Linux!mmfile.c.o \
 $(ObjectDir_Debug)/C-kern!os!Linux!filetest.c.o \
 $(ObjectDir_Debug)/C-kern!os!shared!locale.c.o \
 $(ObjectDir_Debug)/C-kern!os!shared!malloctest.c.o \
 $(ObjectDir_Debug)/C-kern!os!shared!index!splaytree.c.o \
 $(ObjectDir_Debug)/C-kern!math!int!signum.c.o \
 $(ObjectDir_Debug)/C-kern!math!int!power2.c.o \
 $(ObjectDir_Debug)/C-kern!umgebung!log.c.o \
 $(ObjectDir_Debug)/C-kern!umgebung!object_cache.c.o \
 $(ObjectDir_Debug)/C-kern!umgebung!umgebung_default.c.o \
 $(ObjectDir_Debug)/C-kern!umgebung!umgebung.c.o \
 $(ObjectDir_Debug)/C-kern!umgebung!umgebung_testproxy.c.o

Objects_Release := \
 $(ObjectDir_Release)/C-kern!main!test.c.o \
 $(ObjectDir_Release)/C-kern!test!run_unittest.c.o \
 $(ObjectDir_Release)/C-kern!os!Linux!directory.c.o \
 $(ObjectDir_Release)/C-kern!os!Linux!thread.c.o \
 $(ObjectDir_Release)/C-kern!os!Linux!virtmemory.c.o \
 $(ObjectDir_Release)/C-kern!os!Linux!mmfile.c.o \
 $(ObjectDir_Release)/C-kern!os!Linux!filetest.c.o \
 $(ObjectDir_Release)/C-kern!os!shared!locale.c.o \
 $(ObjectDir_Release)/C-kern!os!shared!malloctest.c.o \
 $(ObjectDir_Release)/C-kern!os!shared!index!splaytree.c.o \
 $(ObjectDir_Release)/C-kern!math!int!signum.c.o \
 $(ObjectDir_Release)/C-kern!math!int!power2.c.o \
 $(ObjectDir_Release)/C-kern!umgebung!log.c.o \
 $(ObjectDir_Release)/C-kern!umgebung!object_cache.c.o \
 $(ObjectDir_Release)/C-kern!umgebung!umgebung_default.c.o \
 $(ObjectDir_Release)/C-kern!umgebung!umgebung.c.o \
 $(ObjectDir_Release)/C-kern!umgebung!umgebung_testproxy.c.o

$(Target_Debug): $(Objects_Debug)
$(Target_Debug): | $(ObjectDir_Debug) $(TargetDir_Debug)
	@$(LD_Debug)

$(Target_Release): $(Objects_Release)
$(Target_Release): | $(ObjectDir_Release) $(TargetDir_Release)
	@$(LD_Release)

$(ObjectDir_Debug)/C-kern!main!test.c.o: $(PathOffset)C-kern/main/test.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!test!run_unittest.c.o: $(PathOffset)C-kern/test/run_unittest.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!Linux!directory.c.o: $(PathOffset)C-kern/os/Linux/directory.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!Linux!thread.c.o: $(PathOffset)C-kern/os/Linux/thread.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!Linux!virtmemory.c.o: $(PathOffset)C-kern/os/Linux/virtmemory.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!Linux!mmfile.c.o: $(PathOffset)C-kern/os/Linux/mmfile.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!Linux!filetest.c.o: $(PathOffset)C-kern/os/Linux/filetest.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!shared!locale.c.o: $(PathOffset)C-kern/os/shared/locale.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!shared!malloctest.c.o: $(PathOffset)C-kern/os/shared/malloctest.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!os!shared!index!splaytree.c.o: $(PathOffset)C-kern/os/shared/index/splaytree.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!math!int!signum.c.o: $(PathOffset)C-kern/math/int/signum.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!math!int!power2.c.o: $(PathOffset)C-kern/math/int/power2.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!umgebung!log.c.o: $(PathOffset)C-kern/umgebung/log.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!umgebung!object_cache.c.o: $(PathOffset)C-kern/umgebung/object_cache.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!umgebung!umgebung_default.c.o: $(PathOffset)C-kern/umgebung/umgebung_default.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!umgebung!umgebung.c.o: $(PathOffset)C-kern/umgebung/umgebung.c
	@$(CC_Debug)

$(ObjectDir_Debug)/C-kern!umgebung!umgebung_testproxy.c.o: $(PathOffset)C-kern/umgebung/umgebung_testproxy.c
	@$(CC_Debug)

$(ObjectDir_Release)/C-kern!main!test.c.o: $(PathOffset)C-kern/main/test.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!test!run_unittest.c.o: $(PathOffset)C-kern/test/run_unittest.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!Linux!directory.c.o: $(PathOffset)C-kern/os/Linux/directory.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!Linux!thread.c.o: $(PathOffset)C-kern/os/Linux/thread.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!Linux!virtmemory.c.o: $(PathOffset)C-kern/os/Linux/virtmemory.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!Linux!mmfile.c.o: $(PathOffset)C-kern/os/Linux/mmfile.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!Linux!filetest.c.o: $(PathOffset)C-kern/os/Linux/filetest.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!shared!locale.c.o: $(PathOffset)C-kern/os/shared/locale.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!shared!malloctest.c.o: $(PathOffset)C-kern/os/shared/malloctest.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!os!shared!index!splaytree.c.o: $(PathOffset)C-kern/os/shared/index/splaytree.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!math!int!signum.c.o: $(PathOffset)C-kern/math/int/signum.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!math!int!power2.c.o: $(PathOffset)C-kern/math/int/power2.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!umgebung!log.c.o: $(PathOffset)C-kern/umgebung/log.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!umgebung!object_cache.c.o: $(PathOffset)C-kern/umgebung/object_cache.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!umgebung!umgebung_default.c.o: $(PathOffset)C-kern/umgebung/umgebung_default.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!umgebung!umgebung.c.o: $(PathOffset)C-kern/umgebung/umgebung.c
	@$(CC_Release)

$(ObjectDir_Release)/C-kern!umgebung!umgebung_testproxy.c.o: $(PathOffset)C-kern/umgebung/umgebung_testproxy.c
	@$(CC_Release)

-include $(Objects_Debug:.o=.d)

-include $(Objects_Release:.o=.d)
